name: Build and Push to GitHub Container Registry

on:
  push:
    branches: ["main"]

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # Step 3: Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/omik:latest
          platforms: linux/amd64











# name: Build and Push to Docker Hub

# on:
#   push:
#     branches: ["main"]

# jobs:
#   build-and-push-docker-image:
#     runs-on: ubuntu-latest

#     steps:
#       # Step 1: Checkout repository
#       - name: Checkout repository
#         uses: actions/checkout@v3

#       # Step 2: Log in to Docker Hub
#       - name: Log in to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}

#       # Step 3: Build and push Docker image
#       - name: Build and push Docker image
#         uses: docker/build-push-action@v4
#         with:
#           context: .
#           file: ./Dockerfile
#           push: true
#           tags: ${{ secrets.DOCKERHUB_USERNAME }}/omik:latest
#           platforms: linux/amd64